### ISSUE TITLE
Loading terrain when trying to join the server

### ISSUE THREAD

**Issue by thepenmen22** [artfcl-intlgnce/XXMC#132]
When trying to get into the server, the "Loading terrain" screen stays there for 30+ seconds, sometimes even minutes.

This has to get fixed before the launch. It's not just a problem with me, I know many others have this same issue. Doesn't happen on any other server that I try to join. This might put off a lot of players if they can't join properly.

**Comment by thepenmen22** [comment]
This might be related to this issue as well: when you're at a parkour map, and do /cp leave, or /spawn or whatever to exit from the parkour map, the game will freeze for like 30 seconds. Thought it might just be the parkour plugin.

**Comment by artfcl-intlgnce** [comment]
The loading terrain isn't related to the CP issue -- the CP plugin does take a while to wrap up the region and send u back to a different world via multiverse, so that couple second lag is known and expected. But the loading terrain has historically been an mcmmo-region issue. Often when this happens we can clear the mcmmo regions (they do nothing for us), and that usually helps resolve the issue. Unfortunately without removing MCMMO, the only option may be to have something automatically delete those folders every 48 hours of so. 
But, we can run some tests, I'm pretty sure @Scarsz has run some timing reports on this issue and hasn't found out why. But we do have a lot of plugins, and a complex terrain (our spawn is technically a deep ocean biome so loading the ocean chunks could potentially be a reason as those are pretty heavyweight chunks). But, I'll assign this to @Scarsz and see what he can figure out ((as a detail, it takes me 10-15 seconds to load terrain, it likely depends on the computer type)). Have you adjusted your video MC settings to reduce particles and remove fancy graphics? Only other factor would be the snow particles. 
In any case, I have heard this pain from many players, some even posting in discord screenshots of them stuck on the Loading Terrain Screen. @Scarsz is the right guy for the job.

**Comment by k-lj** [comment]
It takes several tries enable to get onto the server, and when you cant get on it times out, same happend for kaskqde, and me so we need to figure this out before the release, could it be connection throttle?

**Comment by artfcl-intlgnce** [comment]
It *might* have something to do with vehicles.. the timings report show some extra activity around armor stands. Still investigating, agreed this needs to be fixed before launch

**Comment by artfcl-intlgnce** [comment]
Resolved by Scarsz -- deleted /data from BetterVillageWorld
