### ISSUE TITLE
Backpacks

### ISSUE THREAD

**Issue by JoeS8** [artfcl-intlgnce/XXMC#71]
I don't know if this is even possible so feel free to disregard this post if not - but the idea sprang to mind. Having limited inventory space makes drug running a very long and tedious process. Having a 'backpack' of some sort to expand space would be very useful and I suspect very sought after by the selling community. Could be expensive to buy (as expensive as 100k+) but allow more drug movement.

Helps the seller but helps the police officer if they manage to seize it!

Just a thought.

**Comment by Scarsz** [comment]
I actually like this idea a fair bit, backpack plugins already exist because plugins can open virtual inventories to a player which isn't a problem but I'd have to make modifications to FriskStick's jar to have it search backpacks. Definitely doable tho.

**Comment by artfcl-intlgnce** [comment]
Its more than FriskStick.. 
This conflicts with our player vault plugin which is a donor perk, and conflicts with a big point of the server for people to make drug runs and the police catch them for police to make their money. Donor private vaults cant even get opened from spawn nor should backbacks be able to. If people only need to make one trip then open their backback, this makes police making money harder than it is today (which is already too difficult). 
Removing this from priority 1, adding to Backlog. Way more important things like Voting and Server Shop that are actual priority. You can continue in progress for the backpacks but that would only be for factions world, not able to be used for drug runs (nor can /pv or /ec). 
One inventory max drug run, we can talk about doing backpacks for donors instead of /pv .. but still it needs discussion.

**Comment by Scarsz** [comment]
Yeah, I see conflictions with this now too. Maybe we can add FriskStick
support for the personal vault and have some sort of restriction on that;
who knows

**Comment by artfcl-intlgnce** [comment]
I was just thinking add /pv to the blocked commands WG flag for spawn region

**Comment by JoeS8** [comment]
An alternative could possibly be a backpack feature that only allows a certain number of more inventory spaces (like 36 - equivalent of one inventory including hotbar). I didn't mean the ability to move absolutely everything in one whole run because that would be too OP lol. Just one that will slightly aid the drug runners. Without a faction member to help me I am averaging 20-30mins+ in moving one harvest which is a little too long in my opinion. A backpack feature that would cut the time in half would be far more appropriate. Or even chopping off a quarter of the time would be a big help.

**Comment by artfcl-intlgnce** [comment]
You've also made literally millions in the past couple weeks :) I gotta cap
it at 1 inventory per drug run. 36 extra slots is a lot, potentially 50k
ish extra carrying. I mean, the flip side is cops could get double the
payout. Needs review at backlog grooming session

**Comment by JoeS8** [comment]
That's what I was thinking. I didn't want to sound like I wanted this mostly for the seller's benefit. It becomes the seller's worst nightmare if they lose double the payout by getting arrested. A serious incentive for more people to apply to become policeman not to mention. Would increase the competition of getting past cops to sell at jail in the future.

But I very much understand that point. I've made a lot and shouldn't complain about drug running. I'm just trying to stand in the shoes of potential sellers. Some will be completely put off by 20-30 minute running periods.
